[workspace]
resolver = "2"
members = [
    "contracts/group",
    "contracts/semaphore_key_pts",
    "contracts/verifier",
    "contracts/semaphore"
]

[workspace.dependencies]
soroban-sdk = { version = "22.0.0-rc.3.2", features = ["testutils"] }
ed25519-dalek = "2.1.1"